# ==================================Purchase Service - StockPro==================================
spring.application.name=purchase-service
server.port=8084


# =============================PostgreSQL ? own separate database==============================

spring.datasource.url=jdbc:postgresql://localhost:5432/stockpro_purchase_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


# ================================JPA / Hibernate================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================Eureka================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# ================================Feign timeouts================================

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
