spring.application.name=purchase-service
server.port=8084
spring.profiles.default=local

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.openfeign.circuitbreaker.enabled=false
spring.cloud.openfeign.client.config.default.connect-timeout=10000
spring.cloud.openfeign.client.config.default.read-timeout=15000
spring.cloud.openfeign.client.config.warehouse-service.connect-timeout=10000
spring.cloud.openfeign.client.config.warehouse-service.read-timeout=30000

resilience4j.circuitbreaker.instances.warehouse-service.sliding-window-size=20
resilience4j.circuitbreaker.instances.warehouse-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.warehouse-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.warehouse-service.wait-duration-in-open-state=20s
resilience4j.retry.instances.warehouse-service.max-attempts=3
resilience4j.retry.instances.warehouse-service.wait-duration=500ms
resilience4j.timelimiter.instances.warehouse-service.timeout-duration=6s
resilience4j.bulkhead.instances.warehouse-service.max-concurrent-calls=20

resilience4j.circuitbreaker.instances.alert-service.sliding-window-size=20
resilience4j.circuitbreaker.instances.alert-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.alert-service.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.alert-service.wait-duration-in-open-state=15s
resilience4j.retry.instances.alert-service.max-attempts=2
resilience4j.retry.instances.alert-service.wait-duration=300ms
resilience4j.timelimiter.instances.alert-service.timeout-duration=4s
resilience4j.bulkhead.instances.alert-service.max-concurrent-calls=20

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries,ratelimiters,bulkheads
management.endpoint.health.probes.enabled=true
