spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/stockpro_alert_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:stockpro123}}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:alert-service}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

resilience4j.circuitbreaker.instances.warehouseService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.warehouseService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.warehouseService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.warehouseService.sliding-window-size=10
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}

stockpro.clients.product-service.url=${STOCKPRO_PRODUCT_SERVICE_URL:http://product-service:8082}
stockpro.clients.warehouse-service.url=${STOCKPRO_WAREHOUSE_SERVICE_URL:http://warehouse-service:8083}
