
spring.application.name=movement-service
server.port=8086
spring.profiles.default=local

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}

spring.jackson.serialization.write-dates-as-timestamps=false

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1s
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries,ratelimiters,bulkheads
management.endpoint.health.probes.enabled=true
