spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stockpro_purchase_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
stockpro.clients.warehouse-service.url=${STOCKPRO_WAREHOUSE_SERVICE_URL:http://localhost:8083}
stockpro.clients.alert-service.url=${STOCKPRO_ALERT_SERVICE_URL:http://localhost:8087}
