spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/stockpro_purchase_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:stockpro123}}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
stockpro.clients.warehouse-service.url=${STOCKPRO_WAREHOUSE_SERVICE_URL:http://warehouse-service:8083}
stockpro.clients.alert-service.url=${STOCKPRO_ALERT_SERVICE_URL:http://alert-service:8087}
